import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, ManyToOne, OneToMany } from 'typeorm';
import { Tenant } from '../../tenants/tenant.entity';
import { Employee } from '../../hrm/entities/employee.entity';
import { AttendancePolicy } from './attendance-policy.entity';

export enum AttendanceStatus {
  PRESENT = 'present',
  ABSENT = 'absent',
  LATE = 'late',
  HALF_DAY = 'half_day',
  ON_LEAVE = 'on_leave',
  HOLIDAY = 'holiday',
  WEEKEND = 'weekend'
}

export enum CheckType {
  CHECK_IN = 'check_in',
  CHECK_OUT = 'check_out'
}

@Entity('attendances')
export class Attendance {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  employeeId: string;

  @ManyToOne(() => Employee)
  employee: Employee;

  @Column({ type: 'date' })
  attendanceDate: Date;

  @Column({ type: 'timestamp', nullable: true })
  checkInTime: Date;

  @Column({ type: 'timestamp', nullable: true })
  checkOutTime: Date;

  @Column({ type: 'time', nullable: true })
  scheduledCheckIn: Date;

  @Column({ type: 'time', nullable: true })
  scheduledCheckOut: Date;

  @Column({ 
    type: 'enum', 
    enum: AttendanceStatus, 
    default: AttendanceStatus.PRESENT 
  })
  status: AttendanceStatus;

  @Column({ type: 'decimal', precision: 5, scale: 2, default: 0 })
  totalHours: number;

  @Column({ type: 'decimal', precision: 5, scale: 2, default: 0 })
  overtimeHours: number;

  @Column({ type: 'decimal', precision: 5, scale: 2, default: 0 })
  lateMinutes: number;

  @Column({ type: 'decimal', precision: 5, scale: 2, default: 0 })
  earlyDepartureMinutes: number;

  @Column({ type: 'text', nullable: true })
  notes: string;

  @Column({ type: 'json', nullable: true })
  location: {
    latitude?: number;
    longitude?: number;
    address?: string;
    method: 'web' | 'mobile' | 'biometric' | 'rfid';
  };

  @Column({ default: false })
  isAutoGenerated: boolean;

  @Column({ nullable: true })
  approvedById: string;

  @Column({ type: 'timestamp', nullable: true })
  approvedAt: Date;

  @Column({ default: false })
  isProcessed: boolean;

  @Column({ type: 'timestamp', nullable: true })
  processedAt: Date;

  @Column()
  tenantId: string;

  @ManyToOne(() => Tenant)
  tenant: Tenant;

  @ManyToOne(() => AttendancePolicy, { nullable: true })
  policy: AttendancePolicy | null;

  @OneToMany('AttendanceAdjustment', 'attendance')
  adjustments: any[];

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}

@Entity('attendance_logs')
export class AttendanceLog {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  employeeId: string;

  @ManyToOne(() => Employee)
  employee: Employee;

  @Column({ 
    type: 'enum', 
    enum: CheckType 
  })
  checkType: CheckType;

  @Column({ type: 'timestamp' })
  checkTime: Date;

  @Column({ type: 'json', nullable: true })
  location: {
    latitude?: number;
    longitude?: number;
    address?: string;
    method: 'web' | 'mobile' | 'biometric' | 'rfid';
    deviceId?: string;
  };

  @Column({ type: 'text', nullable: true })
  notes: string;

  @Column({ type: 'text', nullable: true })
  ipAddress: string;

  @Column({ default: false })
  isManual: boolean;

  @Column({ nullable: true })
  approvedById: string;

  @Column({ type: 'timestamp', nullable: true })
  approvedAt: Date;

  @Column()
  tenantId: string;

  @ManyToOne(() => Tenant)
  tenant: Tenant;

  @CreateDateColumn()
  createdAt: Date;
}
