import { defineTemplate } from './template-builder';

export const HEALTHCARE_TEMPLATES = [
  defineTemplate({
    id: 'patient-registration',
    name: 'Patient Registration',
    description: 'Register new patient, insurance check, and assign care team.',
    category: 'Healthcare',
    icon: '🏥',
    difficulty: 'beginner',
    estimatedTime: '30-60 min',
    tags: ['Healthcare', 'Patient'],
    industries: ['healthcare'],
    entitySlugs: ['patients'],
    states: [
      { name: 'Registered', key: 'registered', order: 1, description: 'Demographics captured' },
      { name: 'Insurance Verified', key: 'insurance_verified', order: 2, description: 'Coverage OK' },
      { name: 'Active', key: 'active', order: 3, description: 'Ready for care' },
    ],
    transitions: [
      { name: 'Verify', fromState: 'registered', toState: 'insurance_verified', requiredRole: 'Reception' },
      { name: 'Activate', fromState: 'insurance_verified', toState: 'active', requiredRole: 'Admin' },
    ],
    steps: [
      { name: 'Insurance Check', description: 'Validate policy', type: 'task', order: 1, config: { assignToRoles: ['Reception'] } },
      { name: 'Assign Physician', description: 'Primary doctor', type: 'automation', order: 2, config: { action: 'assign_owner' } },
    ],
  }),
  defineTemplate({
    id: 'appointment-booking',
    name: 'Appointment Scheduling',
    description: 'Book appointment, reminders, check-in, and completion.',
    category: 'Healthcare',
    icon: '📅',
    difficulty: 'beginner',
    estimatedTime: '1 day',
    tags: ['Healthcare', 'Appointments'],
    industries: ['healthcare'],
    entitySlugs: ['patients', 'appointments'],
    states: [
      { name: 'Requested', key: 'requested', order: 1, description: 'Booking request' },
      { name: 'Confirmed', key: 'confirmed', order: 2, description: 'Slot confirmed' },
      { name: 'Checked In', key: 'checked_in', order: 3, description: 'Patient arrived' },
      { name: 'Completed', key: 'completed', order: 4, description: 'Visit done' },
    ],
    transitions: [
      { name: 'Confirm', fromState: 'requested', toState: 'confirmed', requiredRole: 'Reception' },
      { name: 'Check In', fromState: 'confirmed', toState: 'checked_in', requiredRole: 'Reception' },
      { name: 'Complete', fromState: 'checked_in', toState: 'completed', requiredRole: 'Clinician' },
    ],
    steps: [
      { name: 'Send Reminder', description: 'SMS/email reminder', type: 'automation', order: 1, config: { action: 'send_notification' } },
      { name: 'Clinical Visit', description: 'Consultation', type: 'task', order: 2, config: { assignToRoles: ['Clinician'] } },
    ],
  }),
  defineTemplate({
    id: 'lab-results-review',
    name: 'Lab Results Review',
    description: 'Lab completes test, clinician reviews, patient notified.',
    category: 'Healthcare',
    icon: '🔬',
    difficulty: 'intermediate',
    estimatedTime: '1-3 days',
    tags: ['Healthcare', 'Lab'],
    industries: ['healthcare'],
    entitySlugs: ['patients', 'lab_orders'],
    states: [
      { name: 'Sample Collected', key: 'sample_collected', order: 1, description: 'Sample taken' },
      { name: 'Processing', key: 'processing', order: 2, description: 'Lab running' },
      { name: 'Review', key: 'review', order: 3, description: 'Doctor review' },
      { name: 'Released', key: 'released', order: 4, description: 'Sent to patient' },
    ],
    transitions: [
      { name: 'Process', fromState: 'sample_collected', toState: 'processing', requiredRole: 'Lab Tech' },
      { name: 'Review', fromState: 'processing', toState: 'review', requiredRole: 'Clinician' },
      { name: 'Release', fromState: 'review', toState: 'released', requiredRole: 'Clinician' },
    ],
    steps: [
      { name: 'Run Tests', description: 'Lab work', type: 'task', order: 1, config: { assignToRoles: ['Lab Tech'] } },
      { name: 'Clinical Review', description: 'Interpret results', type: 'approval', order: 2, config: { assignToRoles: ['Clinician'] } },
      {
        name: 'Notify Patient',
        description: 'Results available',
        type: 'automation',
        order: 3,
        config: {
          action: 'send_email',
          to: '{{email}}',
          template: 'lab_results_ready',
          subject: 'Lab results available',
        },
      },
    ],
  }),
  defineTemplate({
    id: 'clinical-incident-report',
    name: 'Clinical Incident Report',
    description: 'Report safety incident, investigation, and corrective actions.',
    category: 'Healthcare',
    icon: '⚠️',
    difficulty: 'advanced',
    estimatedTime: '3-14 days',
    tags: ['Healthcare', 'Safety', 'Compliance'],
    industries: ['healthcare'],
    entitySlugs: ['incidents', 'patients'],
    states: [
      { name: 'Reported', key: 'reported', order: 1, description: 'Incident filed' },
      { name: 'Investigation', key: 'investigation', order: 2, description: 'Under review' },
      { name: 'Closed', key: 'closed', order: 3, description: 'Actions complete' },
    ],
    transitions: [
      { name: 'Investigate', fromState: 'reported', toState: 'investigation', requiredRole: 'Quality Officer' },
      { name: 'Close', fromState: 'investigation', toState: 'closed', requiredRole: 'Medical Director' },
    ],
    steps: [
      { name: 'Immediate Actions', description: 'Contain risk', type: 'task', order: 1, config: { assignToRoles: ['Nurse Manager'], priority: 'high' } },
      { name: 'Root Cause', description: 'Investigation report', type: 'task', order: 2, config: { assignToRoles: ['Quality Officer'] } },
      { name: 'Director Sign-off', description: 'Close incident', type: 'approval', order: 3, config: { assignToRoles: ['Medical Director'] } },
    ],
  }),
];
