import { defineTemplate } from './template-builder';

/** HR, payroll, leave, expenses — all company types */
export const HR_FINANCE_TEMPLATES = [
  defineTemplate({
    id: 'employee-onboarding',
    name: 'Employee Onboarding',
    description:
      'New hire setup: IT access, HR documents, manager approvals, and system provisioning.',
    category: 'HR Management',
    icon: '👥',
    difficulty: 'intermediate',
    estimatedTime: '2-3 days',
    tags: ['HR', 'Onboarding', 'IT'],
    industries: ['retail', 'manufacturing', 'services', 'healthcare', 'hospitality', 'other'],
    entitySlugs: ['employees'],
    trigger: 'event_based',
    states: [
      { name: 'New Hire', key: 'new_hire', order: 1, description: 'Record created' },
      { name: 'IT Setup', key: 'it_setup', order: 2, description: 'Accounts and access' },
      { name: 'Documentation', key: 'documentation', order: 3, description: 'HR documents' },
      { name: 'Completed', key: 'completed', order: 4, description: 'Onboarding done' },
    ],
    transitions: [
      { name: 'Start IT', fromState: 'new_hire', toState: 'it_setup', requiredRole: 'IT Manager' },
      { name: 'Collect Docs', fromState: 'it_setup', toState: 'documentation', requiredRole: 'HR Manager' },
      { name: 'Complete', fromState: 'documentation', toState: 'completed', requiredRole: 'HR Manager' },
    ],
    steps: [
      {
        name: 'Welcome Email',
        description: 'Send welcome pack',
        type: 'automation',
        order: 1,
        config: {
          action: 'send_email',
          to: '{{email}}',
          template: 'welcome_employee',
          subject: 'Welcome to the team',
        },
      },
      { name: 'IT Account', description: 'Create email and systems', type: 'task', order: 2, config: { assignToRoles: ['IT Manager'], due_in_hours: 24 } },
      { name: 'HR Documents', description: 'Collect signed documents', type: 'task', order: 3, config: { assignToRoles: ['HR Manager'], due_in_hours: 48 } },
    ],
  }),
  defineTemplate({
    id: 'leave-request',
    name: 'Leave Request Approval',
    description: 'Employee leave with manager and HR approval.',
    category: 'HR Management',
    icon: '🏖️',
    difficulty: 'beginner',
    estimatedTime: '1-2 days',
    tags: ['HR', 'Leave'],
    industries: ['retail', 'manufacturing', 'services', 'healthcare', 'hospitality', 'other'],
    entitySlugs: ['employees'],
    states: [
      { name: 'Requested', key: 'requested', order: 1, description: 'Submitted' },
      { name: 'Manager Review', key: 'manager_review', order: 2, description: 'Manager decision' },
      { name: 'Approved', key: 'approved', order: 3, description: 'Approved' },
      { name: 'Rejected', key: 'rejected', order: 4, description: 'Rejected' },
    ],
    transitions: [
      { name: 'To Manager', fromState: 'requested', toState: 'manager_review', requiredRole: 'Manager' },
      { name: 'Approve', fromState: 'manager_review', toState: 'approved', requiredRole: 'Manager' },
      { name: 'Reject', fromState: 'manager_review', toState: 'rejected', requiredRole: 'Manager' },
    ],
    steps: [
      { name: 'Notify Manager', description: 'Alert manager', type: 'automation', order: 1, config: { action: 'send_notification' } },
      { name: 'Manager Approval', description: 'Review leave', type: 'approval', order: 2, config: { assignToRoles: ['Manager'], timeout_hours: 48 } },
    ],
  }),
  defineTemplate({
    id: 'expense-approval',
    name: 'Expense Report Approval',
    description: 'Submit, manager review, and finance approval for reimbursements.',
    category: 'Finance',
    icon: '💰',
    difficulty: 'intermediate',
    estimatedTime: '3-5 days',
    tags: ['Finance', 'Expense'],
    industries: ['services', 'retail', 'manufacturing', 'other'],
    entitySlugs: ['expenses'],
    states: [
      { name: 'Submitted', key: 'submitted', order: 1, description: 'Report filed' },
      { name: 'Manager Review', key: 'manager_review', order: 2, description: 'Manager check' },
      { name: 'Finance', key: 'finance_validation', order: 3, description: 'Finance validation' },
      { name: 'Paid', key: 'paid', order: 4, description: 'Reimbursed' },
    ],
    transitions: [
      { name: 'Manager', fromState: 'submitted', toState: 'manager_review', requiredRole: 'Manager' },
      { name: 'Finance', fromState: 'manager_review', toState: 'finance_validation', requiredRole: 'Finance Manager' },
      { name: 'Pay', fromState: 'finance_validation', toState: 'paid', requiredRole: 'Accountant' },
    ],
    steps: [
      { name: 'Manager Approval', description: 'Manager signs off', type: 'approval', order: 1, config: { assignToRoles: ['Manager'] } },
      { name: 'Finance Check', description: 'Validate receipts', type: 'task', order: 2, config: { assignToRoles: ['Finance Manager'] } },
      { name: 'Process Payment', description: 'Pay employee', type: 'task', order: 3, config: { assignToRoles: ['Accountant'] } },
    ],
  }),
  defineTemplate({
    id: 'procurement-approval',
    name: 'Procurement Request',
    description: 'Purchase requests with budget check, quotes, and management approval.',
    category: 'Procurement',
    icon: '📦',
    difficulty: 'advanced',
    estimatedTime: '5-10 days',
    tags: ['Procurement', 'Purchase'],
    industries: ['retail', 'manufacturing'],
    entitySlugs: ['products', 'suppliers'],
    states: [
      { name: 'Requested', key: 'requested', order: 1, description: 'Request raised' },
      { name: 'Budget OK', key: 'budget_approval', order: 2, description: 'Budget approved' },
      { name: 'Approved', key: 'approved', order: 3, description: 'Ready to order' },
      { name: 'Ordered', key: 'ordered', order: 4, description: 'PO sent' },
    ],
    transitions: [
      { name: 'Budget', fromState: 'requested', toState: 'budget_approval', requiredRole: 'Budget Manager' },
      { name: 'Approve', fromState: 'budget_approval', toState: 'approved', requiredRole: 'Procurement Manager' },
      { name: 'Order', fromState: 'approved', toState: 'ordered', requiredRole: 'Procurement Manager' },
    ],
    steps: [
      { name: 'Budget Check', description: 'Auto budget rules', type: 'automation', order: 1, config: { action: 'check_budget' } },
      { name: 'Budget Approval', description: 'Manager approves spend', type: 'approval', order: 2, config: { assignToRoles: ['Budget Manager'] } },
      { name: 'Place Order', description: 'Create PO', type: 'task', order: 3, config: { assignToRoles: ['Procurement Manager'] } },
    ],
  }),
  defineTemplate({
    id: 'payroll-processing',
    name: 'Monthly Payroll Processing',
    description: 'HR prepares payroll, finance reviews, and approves disbursement.',
    category: 'Finance',
    icon: '💳',
    difficulty: 'intermediate',
    estimatedTime: '3-5 days',
    tags: ['HR', 'Payroll', 'Finance'],
    industries: ['retail', 'manufacturing', 'services', 'healthcare', 'other'],
    entitySlugs: ['employees'],
    states: [
      { name: 'Draft', key: 'draft', order: 1, description: 'Payroll draft' },
      { name: 'HR Review', key: 'hr_review', order: 2, description: 'HR verified' },
      { name: 'Finance Approval', key: 'finance_approval', order: 3, description: 'Approved to pay' },
      { name: 'Disbursed', key: 'disbursed', order: 4, description: 'Paid out' },
    ],
    transitions: [
      { name: 'HR Review', fromState: 'draft', toState: 'hr_review', requiredRole: 'HR Manager' },
      { name: 'Finance', fromState: 'hr_review', toState: 'finance_approval', requiredRole: 'Finance Manager' },
      { name: 'Pay', fromState: 'finance_approval', toState: 'disbursed', requiredRole: 'Accountant' },
    ],
    steps: [
      { name: 'HR Validation', description: 'Check attendance and deductions', type: 'task', order: 1, config: { assignToRoles: ['HR Manager'] } },
      { name: 'Finance Approval', description: 'Approve payroll run', type: 'approval', order: 2, config: { assignToRoles: ['Finance Manager'] } },
    ],
  }),
];
