import { defineTemplate } from './template-builder';

export const MANUFACTURING_TEMPLATES = [
  defineTemplate({
    id: 'quality-control-inspection',
    name: 'Quality Control Inspection',
    description: 'Batch inspection, QA sign-off, and release or reject.',
    category: 'Manufacturing',
    icon: '✅',
    difficulty: 'intermediate',
    estimatedTime: '1-2 days',
    tags: ['QA', 'Quality', 'Production'],
    industries: ['manufacturing'],
    entitySlugs: ['products', 'quality_inspections'],
    states: [
      { name: 'Pending QC', key: 'pending_qc', order: 1, description: 'Awaiting inspection' },
      { name: 'In Inspection', key: 'in_inspection', order: 2, description: 'QC in progress' },
      { name: 'Released', key: 'released', order: 3, description: 'Passed' },
      { name: 'Rejected', key: 'rejected', order: 4, description: 'Failed QC' },
    ],
    transitions: [
      { name: 'Start', fromState: 'pending_qc', toState: 'in_inspection', requiredRole: 'QA Inspector' },
      { name: 'Release', fromState: 'in_inspection', toState: 'released', requiredRole: 'QA Manager' },
      { name: 'Reject', fromState: 'in_inspection', toState: 'rejected', requiredRole: 'QA Manager' },
    ],
    steps: [
      { name: 'Inspect Batch', description: 'Run checklist', type: 'task', order: 1, config: { assignToRoles: ['QA Inspector'] } },
      { name: 'QA Approval', description: 'Manager release', type: 'approval', order: 2, config: { assignToRoles: ['QA Manager'] } },
    ],
  }),
  defineTemplate({
    id: 'equipment-maintenance',
    name: 'Equipment Maintenance Work Order',
    description: 'Report breakdown, assign technician, complete repair.',
    category: 'Manufacturing',
    icon: '🔩',
    difficulty: 'intermediate',
    estimatedTime: '1-5 days',
    tags: ['Maintenance', 'Equipment'],
    industries: ['manufacturing'],
    entitySlugs: ['work_orders', 'equipment'],
    states: [
      { name: 'Reported', key: 'reported', order: 1, description: 'Issue logged' },
      { name: 'Assigned', key: 'assigned', order: 2, description: 'Technician assigned' },
      { name: 'In Repair', key: 'in_repair', order: 3, description: 'Work ongoing' },
      { name: 'Closed', key: 'closed', order: 4, description: 'Fixed' },
    ],
    transitions: [
      { name: 'Assign', fromState: 'reported', toState: 'assigned', requiredRole: 'Maintenance Lead' },
      { name: 'Start', fromState: 'assigned', toState: 'in_repair', requiredRole: 'Technician' },
      { name: 'Close', fromState: 'in_repair', toState: 'closed', requiredRole: 'Maintenance Lead' },
    ],
    steps: [
      { name: 'Assign Tech', description: 'Schedule visit', type: 'task', order: 1, config: { assignToRoles: ['Maintenance Lead'] } },
      { name: 'Repair Work', description: 'Complete fix', type: 'task', order: 2, config: { assignToRoles: ['Technician'], due_in_hours: 24 } },
    ],
  }),
  defineTemplate({
    id: 'production-batch-release',
    name: 'Production Batch Release',
    description: 'Manufacturing order from planning through production to finished goods.',
    category: 'Manufacturing',
    icon: '🏭',
    difficulty: 'advanced',
    estimatedTime: '3-14 days',
    tags: ['Production', 'Batch'],
    industries: ['manufacturing'],
    entitySlugs: ['products', 'production_orders'],
    states: [
      { name: 'Planned', key: 'planned', order: 1, description: 'Scheduled' },
      { name: 'In Production', key: 'in_production', order: 2, description: 'Running' },
      { name: 'QC Hold', key: 'qc_hold', order: 3, description: 'Awaiting QC' },
      { name: 'Released', key: 'released', order: 4, description: 'To inventory' },
    ],
    transitions: [
      { name: 'Start', fromState: 'planned', toState: 'in_production', requiredRole: 'Production Manager' },
      { name: 'QC', fromState: 'in_production', toState: 'qc_hold', requiredRole: 'Production Manager' },
      { name: 'Release', fromState: 'qc_hold', toState: 'released', requiredRole: 'QA Manager' },
    ],
    steps: [
      { name: 'Material Issue', description: 'Issue raw materials', type: 'task', order: 1, config: { assignToRoles: ['Warehouse'] } },
      { name: 'Run Production', description: 'Shop floor', type: 'task', order: 2, config: { assignToRoles: ['Production Manager'] } },
      { name: 'QC Release', description: 'Final approval', type: 'approval', order: 3, config: { assignToRoles: ['QA Manager'] } },
    ],
  }),
  defineTemplate({
    id: 'supplier-onboarding',
    name: 'Supplier Onboarding',
    description: 'Register new vendor, compliance check, and approve for POs.',
    category: 'Procurement',
    icon: '🤝',
    difficulty: 'intermediate',
    estimatedTime: '5-10 days',
    tags: ['Suppliers', 'Vendor'],
    industries: ['manufacturing', 'retail'],
    entitySlugs: ['suppliers'],
    states: [
      { name: 'Application', key: 'application', order: 1, description: 'Vendor applied' },
      { name: 'Compliance', key: 'compliance', order: 2, description: 'Docs reviewed' },
      { name: 'Approved', key: 'approved', order: 3, description: 'Active vendor' },
    ],
    transitions: [
      { name: 'Review', fromState: 'application', toState: 'compliance', requiredRole: 'Procurement Manager' },
      { name: 'Approve', fromState: 'compliance', toState: 'approved', requiredRole: 'Finance Manager' },
    ],
    steps: [
      { name: 'Collect Documents', description: 'Tax, licenses', type: 'task', order: 1, config: { assignToRoles: ['Procurement Manager'] } },
      { name: 'Finance Approval', description: 'Approve vendor', type: 'approval', order: 2, config: { assignToRoles: ['Finance Manager'] } },
    ],
  }),
];
